
---
#
# Reporting Microservice Deployment + Service
#
kind: Service
apiVersion: v1
metadata:
  name: reporting-api
  namespace: ecommerce
  labels:
    app: reporting-api
    tier: backend
spec:
  selector:
    app: reporting-api
    tier: backend
  ports:
  - name: reporting-api
    protocol: TCP
    port: 8084
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-api
  namespace: ecommerce
spec:
  selector:
    matchLabels:
      app: reporting-api
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: reporting-api
        tier: backend
    spec:
      containers:
      - name: reporting-api
        image: $$REGISTRY_SERVERreporting-api:$$IMAGE_VERSION
        imagePullPolicy: $$IMAGE_PULL_POLICY
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "$$ENVIRONMENT_NAME"
        - name: ASPNETCORE_ORCHESTRATOR
          value: "k8s"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3